# Linux Container Build Workflow
#
# Complete Linux build pipeline using Docker containers.
# All jobs run on Ubuntu runners with docker run commands.
# Build scripts are executed inside containers with workspace mounted.
#
name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/${GITHUB_REPOSITORY}

jobs:
  determine-tag:
    name: Determine Image Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      repo: ${{ steps.tag.outputs.repo }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate tag and repo name
        id: tag
        run: |
          VERSION=$(cargo pkgid | cut -d@ -f2)
          echo "tag=dev-${VERSION}" >> $GITHUB_OUTPUT
          echo "repo=${REGISTRY}/realistic-spell-fps-base" >> $GITHUB_OUTPUT
          echo "Using tag: dev-${VERSION}"
          echo "Using repo: ${REGISTRY}/realistic-spell-fps-base"

  build-base-image:
    name: Build Base Image
    runs-on: ubuntu-latest
    needs: determine-tag
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push base builder
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.devcontainer/base-builder-linux.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ needs.determine-tag.outputs.repo }}:${{ needs.determine-tag.outputs.tag }}
            ${{ env.REGISTRY }}/${{ needs.determine-tag.outputs.repo }}:latest
          cache-from: type=gha,scope=base-linux
          cache-to: type=gha,mode=max,scope=base-linux

  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    needs: [determine-tag, build-base-image]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull base builder image
        run: docker pull ${{ env.REGISTRY }}/${{ needs.determine-tag.outputs.repo }}/base-builder-linux:${{ needs.determine-tag.outputs.tag }}
      
      - name: Run build in container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ${{ env.REGISTRY }}/${{ needs.determine-tag.outputs.repo }}/base-builder-linux:${{ needs.determine-tag.outputs.tag }} \
            /usr/local/bin/build.sh
      
      - name: Upload server binary
        uses: actions/upload-artifact@v4
        with:
          name: server-linux
          path: target/release/server
      
      - name: Upload client binary
        uses: actions/upload-artifact@v4
        with:
          name: client-linux
          path: target/release/client

  runtime-check:
    name: Runtime Check
    runs-on: ubuntu-latest
    needs: build-binaries
    steps:
      - name: Download server binary
        uses: actions/download-artifact@v4
        with:
          name: server-linux
          path: ./bin
      
      - name: Download client binary
        uses: actions/download-artifact@v4
        with:
          name: client-linux
          path: ./bin
      
      - name: Set executable permissions
        run: chmod +x ./bin/server ./bin/client
      
      - name: Test server runs in minimal environment
        run: timeout 5s ./bin/server || [ $? -eq 124 ] || [ $? -eq 143 ]
      
      - name: Test client runs in minimal environment
        run: timeout 5s ./bin/client || [ $? -eq 124 ] || [ $? -eq 143 ]
