# CI Workflow
#
# Runs tests and linting inside Docker containers for consistency.
# Uses pre-built base builder images from GHCR.
#
name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}
  CARGO_TERM_COLOR: always

jobs:
  test-in-container:
    name: Test (in Linux container)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/base-builder-linux:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run tests
        run: cargo test --workspace --verbose --no-fail-fast --no-default-features

  lint-in-container:
    name: Lint (in Linux container)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/base-builder-linux:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check formatting
        run: cargo fmt --all -- --check
      
      - name: Run clippy
        run: cargo clippy --workspace --all-targets --no-default-features -- -D warnings
        continue-on-error: true

  build-in-container:
    name: Build (in Linux container)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/base-builder-linux:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build workspace
        run: cargo build --workspace --verbose --no-default-features
      
      - name: Build release
        run: cargo build --workspace --release --verbose --no-default-features
