# Multi-Platform Docker Build Workflow
#
# Production-ready, platform-specific Docker builds
# Runs on pushes to master/main and on version tags
#
# Use this for: Production deployments, multi-platform support
# Use docker.yml for: Quick testing, single-platform development builds
#
# Platform-specific images:
#   - client-linux: Linux AMD64 client
#   - server-linux: Linux AMD64 server
#   Note: Windows builds are disabled due to buildkit compatibility issues with Windows containers
#         See: https://github.com/docker/buildx/issues/132
#
# Published to: Configurable registry (default: GitHub Container Registry)
# Configuration: Uses DOCKER_REGISTRY, DOCKER_USERNAME, DOCKER_PASSWORD secrets
#
# Cargo.lock handling:
#   - Dockerfiles use COPY Cargo.lock* pattern to handle missing lock file
#   - If missing, cargo will generate it during docker build
#
name: Multi-Platform Docker Build

on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master, main ]

env:
  # Allow custom registry via secrets, default to GHCR
  REGISTRY: ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}
  REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME || github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD || secrets.GITHUB_TOKEN }}

jobs:
  build-client-linux:
    name: Build Client (Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/client-linux
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.devcontainer/client-linux.Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-server-linux:
    name: Build Server (Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/server-linux
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.devcontainer/server-linux.Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Windows builds are currently disabled due to buildkit compatibility issues
  # Error: "no matching manifest for windows/amd64 10.0.20348 in the manifest list entries"
  # To re-enable, uncomment the jobs below and resolve buildkit Windows container support
  #
  # build-client-windows:
  #   name: Build Client (Windows)
  #   runs-on: windows-2022
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     
  #     - name: Log in to Container Registry
  #       if: github.event_name != 'pull_request'
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ env.REGISTRY_USERNAME }}
  #         password: ${{ env.REGISTRY_PASSWORD }}
  #     
  #     - name: Extract metadata
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ github.repository }}/client-windows
  #         tags: |
  #           type=ref,event=branch
  #           type=ref,event=pr
  #           type=semver,pattern={{version}}
  #           type=semver,pattern={{major}}.{{minor}}
  #           type=raw,value=latest,enable={{is_default_branch}}
  #     
  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         file: ./.devcontainer/client-windows.Dockerfile
  #         platforms: windows/amd64
  #         push: ${{ github.event_name != 'pull_request' }}
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}
  #
  # build-server-windows:
  #   name: Build Server (Windows)
  #   runs-on: windows-2022
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     
  #     - name: Log in to Container Registry
  #       if: github.event_name != 'pull_request'
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ env.REGISTRY_USERNAME }}
  #         password: ${{ env.REGISTRY_PASSWORD }}
  #     
  #     - name: Extract metadata
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ github.repository }}/server-windows
  #         tags: |
  #           type=ref,event=branch
  #           type=ref,event=pr
  #           type=semver,pattern={{version}}
  #           type=semver,pattern={{major}}.{{minor}}
  #           type=raw,value=latest,enable={{is_default_branch}}
  #     
  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         file: ./.devcontainer/server-windows.Dockerfile
  #         platforms: windows/amd64
  #         push: ${{ github.event_name != 'pull_request' }}
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}
