# Docker Build Workflow
#
# Quick single-platform Docker builds for development.
# Published to: GitHub Container Registry (ghcr.io)
#
name: Docker Build

on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*'
    paths-ignore:
      - '.devcontainer/base-builder-linux.Dockerfile'
      - '.devcontainer/base-builder-windows.Dockerfile'
      - '.github/workflows/build-base-images.yml'
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '.devcontainer/base-builder-linux.Dockerfile'
      - '.devcontainer/base-builder-windows.Dockerfile'
      - '.github/workflows/build-base-images.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for client
        id: meta-client
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/client
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build and push client
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.devcontainer/client.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-client.outputs.tags }}
          labels: ${{ steps.meta-client.outputs.labels }}
          cache-from: type=gha,scope=client
          cache-to: type=gha,mode=max,scope=client
          build-args: |
            BASE_BUILDER_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/base-builder-linux:latest
      
      - name: Extract metadata for server
        id: meta-server
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/server
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build and push server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.devcontainer/server.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}
          cache-from: type=gha,scope=server
          cache-to: type=gha,mode=max,scope=server
          build-args: |
            BASE_BUILDER_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/base-builder-linux:latest
