# Multi-Platform Docker Build Workflow
#
# Production-ready, platform-specific Docker builds
# Runs on pushes to master/main and on version tags
#
# Use this for: Production deployments, multi-platform support
# Use docker.yml for: Quick testing, single-platform development builds
#
# Platform-specific images:
#   - client-linux: Linux AMD64 client
#   - server-linux: Linux AMD64 server
#   - client-windows: Windows client
#   - server-windows: Windows server
#
# Uses pre-built base builder images from Docker Hub or custom registry
# Base images are built separately via build-base-images.yml workflow
#
# Published to: Configurable registry (default: GitHub Container Registry)
# Configuration: Uses DOCKER_REGISTRY, DOCKER_USERNAME, DOCKER_PASSWORD secrets
#
# Cargo.lock handling:
#   - Dockerfiles use COPY Cargo.lock* pattern to handle missing lock file
#   - If missing, cargo will generate it during docker build
#
name: Multi-Platform Docker Build

on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*'
    # Don't trigger when only base Dockerfiles change (those are handled by build-base-images.yml)
    paths-ignore:
      - '.devcontainer/base-builder-linux.Dockerfile'
      - '.devcontainer/base-builder-windows.Dockerfile'
      - '.github/workflows/build-base-images.yml'
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '.devcontainer/base-builder-linux.Dockerfile'
      - '.devcontainer/base-builder-windows.Dockerfile'
      - '.github/workflows/build-base-images.yml'

env:
  # Allow custom registry via secrets, default to GHCR
  REGISTRY: ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}
  REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME || github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD || secrets.GITHUB_TOKEN }}
  # Base builder images registry (Docker Hub by default)
  BASE_REGISTRY: ${{ secrets.DOCKER_REGISTRY || 'docker.io' }}
  BASE_REPO: ${{ secrets.DOCKERHUB_USERNAME || github.repository }}

jobs:
  build-client-linux:
    name: Build Client (Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/client-linux
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.devcontainer/client-linux.Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BASE_BUILDER_IMAGE=${{ env.BASE_REGISTRY }}/${{ env.BASE_REPO }}/base-builder-linux:latest

  build-server-linux:
    name: Build Server (Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/server-linux
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.devcontainer/server-linux.Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BASE_BUILDER_IMAGE=${{ env.BASE_REGISTRY }}/${{ env.BASE_REPO }}/base-builder-linux:latest

  # Windows builds use native Docker (not BuildKit) due to compatibility issues
  # Native Docker daemon on windows-2022 runners works reliably for Windows containers
  build-client-windows:
    name: Build Client (Windows)
    runs-on: windows-2022
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Skip BuildKit setup - use native Docker daemon on Windows
      # BuildKit doesn't support Windows containers properly on GitHub runners
      
      - name: Prepare Docker tags
        id: prepare
        shell: bash
        run: |
          # Convert repository name to lowercase and sanitize ref name for Docker tags
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          REF_SAFE=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]' | sed 's/\//-/g')
          echo "repo=${REPO_LOWER}" >> $GITHUB_OUTPUT
          echo "tag=${REF_SAFE}" >> $GITHUB_OUTPUT
      
      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ env.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ env.REGISTRY_USERNAME }} --password-stdin
      
      - name: Build Windows client image
        run: |
          docker build -f .devcontainer/client-windows.Dockerfile --build-arg BASE_BUILDER_IMAGE=${{ env.BASE_REGISTRY }}/${{ steps.prepare.outputs.repo }}/base-builder-windows:latest -t ${{ env.REGISTRY }}/${{ steps.prepare.outputs.repo }}/client-windows:${{ steps.prepare.outputs.tag }} .
      
      - name: Push Windows client image
        if: github.event_name != 'pull_request'
        run: |
          docker push ${{ env.REGISTRY }}/${{ steps.prepare.outputs.repo }}/client-windows:${{ steps.prepare.outputs.tag }}

  build-server-windows:
    name: Build Server (Windows)
    runs-on: windows-2022
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Skip BuildKit setup - use native Docker daemon on Windows
      # BuildKit doesn't support Windows containers properly on GitHub runners
      
      - name: Prepare Docker tags
        id: prepare
        shell: bash
        run: |
          # Convert repository name to lowercase and sanitize ref name for Docker tags
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          REF_SAFE=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]' | sed 's/\//-/g')
          echo "repo=${REPO_LOWER}" >> $GITHUB_OUTPUT
          echo "tag=${REF_SAFE}" >> $GITHUB_OUTPUT
      
      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ env.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ env.REGISTRY_USERNAME }} --password-stdin
      
      - name: Build Windows server image
        run: |
          docker build -f .devcontainer/server-windows.Dockerfile --build-arg BASE_BUILDER_IMAGE=${{ env.BASE_REGISTRY }}/${{ steps.prepare.outputs.repo }}/base-builder-windows:latest -t ${{ env.REGISTRY }}/${{ steps.prepare.outputs.repo }}/server-windows:${{ steps.prepare.outputs.tag }} .
      
      - name: Push Windows server image
        if: github.event_name != 'pull_request'
        run: |
          docker push ${{ env.REGISTRY }}/${{ steps.prepare.outputs.repo }}/server-windows:${{ steps.prepare.outputs.tag }}
